### ISSUE TITLE
ImportError: No module named pytz

### ISSUE THREAD

**Issue by ghost** [kiritbasu/Fake-Apache-Log-Generator#16]
Executing this command gives:

$ python apache-fake-log-gen.py -n 100 -o GZ -s 10

Traceback (most recent call last):
  File "apache-fake-log-gen.py", line 4, in <module>
    import pytz
ImportError: No module named pytz

I'm on Amazon Linux ami-0f2176987ee50226e

**Comment by ghost** [comment]
This command `pip install -r requirements.txt` needs to be `sudo pip install -r requirements.txt`

**Comment by EndrisKerga** [comment]
sudo pip install -r requirements.txt works. After that, you can generate your logs.
python apache-fake-log-gen.py -n 20

**Comment by mukscool** [comment]
Hello All, I am getting below error while executing on Amazon Linux AMI
Traceback (most recent call last):
  File "apache-fake-log-gen.py", line 4, in <module>
    import pytz
ImportError: No module named pytz

Also I am not able to install pip. Can someone help ?

**Comment by bigcumulus** [comment]
@mukscool `sudo yum install pytz` for installing python packages on Amazon Linux AMI

Additionally, running the command: `sudo yum install python-pip` will allow you to utilize pip commands in the instance (change [python > python2, python3] or [pip >pip3] in that command if you run into versioning issues . You will need to use `sudo` before your `pip` and `yum` commands for root access.
