### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by kurvaraviteja355** [kiritbasu/Fake-Apache-Log-Generator#20]
I installed all the dependencies but i dont know why i am getting the runtime error
C:\Users\home\Fake-Apache-Log-Generator>python apache-fake-log-gen.py
Traceback (most recent call last):
  File "C:\Users\home\Fake-Apache-Log-Generator\apache-fake-log-gen.py", line 29, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\home\Fake-Apache-Log-Generator\apache-fake-log-gen.py", line 62, in <module>
    for case in switch(output_type):
RuntimeError: generator raised StopIteration

**Comment by john-corcoran** [comment]
Hi, as a workaround, you can run in Python 3.6 or earlier and this error won't be thrown (the error may be related to new behaviour in Python 3.7 and later, as per https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app)
